In [1]:
# Load Libraries

import pandas as pd
import plotly.graph_objects as go
import numpy as np 
import scipy                       # Statistical inference

import datetime as datetime 
import wget
import zipfile
import os

import matplotlib.pyplot as plt
import seaborn as sns 
from datetime import datetime,timedelta
import zipfile, requests, io
import os 
import warnings
from datetime import date

In [2]:
# Download the entire raw data and build a new dataset with specific selections - as reported!!

# Data address: https://www.gob.mx/salud/documentos/datos-abiertos-152127

# Dates from when we have historical data

start_date = date(2020, 4, 15)
end_date = date(2020, 10, 5)

dateseries = [date.fromordinal(i) for i in range(start_date.toordinal(), end_date.toordinal()+1)]

# Empty dataset
lista = ['FECHA_ACTUALIZACION','ID_REGISTRO','RESULTADO','FECHA_INGRESO','FECHA_DEF']
df         = pd.DataFrame(index=dateseries,columns=lista)
df         = df.reset_index()
df         = df.rename(columns={"index": "date"})
df['date'] = pd.to_datetime(df['date'])
appended_data=pd.DataFrame()
# Loop work
for i in dateseries:
    print('working on:',i,i.month,i.day)
    
    # Extract month and day
    if i.month<10:
        month = str(0)+str(i.month)
    else:
        month = str(i.month)
    if i.day<10:    
        day   = str(0)+str(i.day)
    else:   
        day   = str(i.day)
    
    # Apply them to the url and file to be downloaded
    filenamezip = 'datos_abiertos_covid19_'+day+'.'+month+'.2020.zip'
    url = 'http://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/historicos/'+month+'/'+filenamezip
    filenamezip = wget.download(url)
    with zipfile.ZipFile(filenamezip, 'r') as zip_ref:
        zip_ref.extractall()
        
    # This is the filename inside the zip file    
    filename = '20'+month+day+'COVID19MEXICO.csv'

    # Read data in pandas
    mx = pd.read_csv(filename,encoding='latin1')
    
    #ir juntando todas las bases 
    appended_data = appended_data.append(mx[lista])

working on: 2020-04-15 4 15
working on: 2020-04-16 4 16
working on: 2020-04-17 4 17
working on: 2020-04-18 4 18

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (33) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

working on: 2020-04-19 4 19
working on: 2020-04-20 4 20
working on: 2020-04-21 4 21
working on: 2020-04-22 4 22
working on: 2020-04-23 4 23
working on: 2020-04-24 4 24
working on: 2020-04-25 4 25
working on: 2020-04-26 4 26
working on: 2020-04-27 4 27
working on: 2020-04-28 4 28
working on: 2020-04-29 4 29
working on: 2020-04-30 4 30
working on: 2020-05-01 5 1
working on: 2020-05-02 5 2
working on: 2020-05-03 5 3
working on: 2020-05-04 5 4
working on: 2020-05-05 5 5
working on: 2020-05-06 5 6
working on: 2020-05-07 5 7
working on: 2020-05-08 5 8
working on: 2020-05-09 5 9
working on: 2020-05-10 5 10
working on: 2020-05-11 5 11
working on: 2020-05-12 5 12
working on: 2020-05-13 5 13
working on: 2020-05-14 5 14
working on: 2020-05-15 5 15
working on: 2020-05-16 5 16
working on: 2020-05-17 5 17
working on: 2020-05-18 5 18
working on: 2020-05-19 5 19
working on: 2020-05-20 5 20
working on: 2020-05-21 5 21
working on: 2020-05-22 5 22
working on: 2020-05-23 5 23
working on: 2020-05-24 5 24
working on: 2020-05-25 5 25
working on: 2020-05-26 5 26
working on: 2020-05-27 5 27
working on: 2020-05-28 5 28
working on: 2020-05-29 5 29
working on: 2020-05-30 5 30
working on: 2020-05-31 5 31
working on: 2020-06-01 6 1
working on: 2020-06-02 6 2
working on: 2020-06-03 6 3
working on: 2020-06-04 6 4
working on: 2020-06-05 6 5
working on: 2020-06-06 6 6
working on: 2020-06-07 6 7
working on: 2020-06-08 6 8
working on: 2020-06-09 6 9
working on: 2020-06-10 6 10
working on: 2020-06-11 6 11
working on: 2020-06-12 6 12
working on: 2020-06-13 6 13
working on: 2020-06-14 6 14
working on: 2020-06-15 6 15
working on: 2020-06-16 6 16
working on: 2020-06-17 6 17
working on: 2020-06-18 6 18
working on: 2020-06-19 6 19
working on: 2020-06-20 6 20
working on: 2020-06-21 6 21
working on: 2020-06-22 6 22
working on: 2020-06-23 6 23
working on: 2020-06-24 6 24
working on: 2020-06-25 6 25
working on: 2020-06-26 6 26
working on: 2020-06-27 6 27
working on: 2020-06-28 6 28
working on: 2020-06-29 6 29
working on: 2020-06-30 6 30
working on: 2020-07-01 7 1
working on: 2020-07-02 7 2
working on: 2020-07-03 7 3
working on: 2020-07-04 7 4
working on: 2020-07-05 7 5
working on: 2020-07-06 7 6
working on: 2020-07-07 7 7
working on: 2020-07-08 7 8
working on: 2020-07-09 7 9
working on: 2020-07-10 7 10
working on: 2020-07-11 7 11
working on: 2020-07-12 7 12
working on: 2020-07-13 7 13
working on: 2020-07-14 7 14
working on: 2020-07-15 7 15
working on: 2020-07-16 7 16
working on: 2020-07-17 7 17
working on: 2020-07-18 7 18
working on: 2020-07-19 7 19
working on: 2020-07-20 7 20
working on: 2020-07-21 7 21
working on: 2020-07-22 7 22
working on: 2020-07-23 7 23
working on: 2020-07-24 7 24
working on: 2020-07-25 7 25
working on: 2020-07-26 7 26
working on: 2020-07-27 7 27
working on: 2020-07-28 7 28
working on: 2020-07-29 7 29
working on: 2020-07-30 7 30
working on: 2020-07-31 7 31
working on: 2020-08-01 8 1
working on: 2020-08-02 8 2
working on: 2020-08-03 8 3
working on: 2020-08-04 8 4
working on: 2020-08-05 8 5
working on: 2020-08-06 8 6
working on: 2020-08-07 8 7
working on: 2020-08-08 8 8
working on: 2020-08-09 8 9
working on: 2020-08-10 8 10
working on: 2020-08-11 8 11
working on: 2020-08-12 8 12
working on: 2020-08-13 8 13
working on: 2020-08-14 8 14
working on: 2020-08-15 8 15
working on: 2020-08-16 8 16
working on: 2020-08-17 8 17
working on: 2020-08-18 8 18
working on: 2020-08-19 8 19
working on: 2020-08-20 8 20
working on: 2020-08-21 8 21
working on: 2020-08-22 8 22
working on: 2020-08-23 8 23
working on: 2020-08-24 8 24
working on: 2020-08-25 8 25
working on: 2020-08-26 8 26
working on: 2020-08-27 8 27
working on: 2020-08-28 8 28
working on: 2020-08-29 8 29
working on: 2020-08-30 8 30
working on: 2020-08-31 8 31
working on: 2020-09-01 9 1
working on: 2020-09-02 9 2
working on: 2020-09-03 9 3
working on: 2020-09-04 9 4
working on: 2020-09-05 9 5
working on: 2020-09-06 9 6
working on: 2020-09-07 9 7
working on: 2020-09-08 9 8
working on: 2020-09-09 9 9
working on: 2020-09-10 9 10
working on: 2020-09-11 9 11
working on: 2020-09-12 9 12
working on: 2020-09-13 9 13
working on: 2020-09-14 9 14
working on: 2020-09-15 9 15
working on: 2020-09-16 9 16
working on: 2020-09-17 9 17
working on: 2020-09-18 9 18
working on: 2020-09-19 9 19
working on: 2020-09-20 9 20
working on: 2020-09-21 9 21
working on: 2020-09-22 9 22
working on: 2020-09-23 9 23
working on: 2020-09-24 9 24
working on: 2020-09-25 9 25
working on: 2020-09-26 9 26
working on: 2020-09-27 9 27
working on: 2020-09-28 9 28
working on: 2020-09-29 9 29
working on: 2020-09-30 9 30
working on: 2020-10-01 10 1
working on: 2020-10-02 10 2
working on: 2020-10-03 10 3
working on: 2020-10-04 10 4
working on: 2020-10-05 10 5

In [3]:
#Guardar Base de datos para no correrla siempre:
df.to_csv(r"/Users/dcastanog/Desktop/Python/all_dataframes.csv")

In [4]:
#Todas las bases juntas (de 15 de abril al 5 de octubre)
appended_data

        FECHA_ACTUALIZACION ID_REGISTRO  RESULTADO FECHA_INGRESO   FECHA_DEF
0                2020-04-19      09e8dc          1    2020-04-09  9999-99-99
1                2020-04-19      0efbaf          1    2020-04-06  9999-99-99
2                2020-04-19      091a48          2    2020-04-06  9999-99-99
3                2020-04-19      1a5595          3    2020-04-15  9999-99-99
4                2020-04-19      13236c          2    2020-04-02  9999-99-99
...                     ...         ...        ...           ...         ...
1758577          2020-10-05      206daa          3    2020-10-04  9999-99-99
1758578          2020-10-05      3d5b93          3    2020-10-04  9999-99-99
1758579          2020-10-05      4060ae          3    2020-10-04  9999-99-99
1758580          2020-10-05      3f1bc7          3    2020-09-28  9999-99-99
1758581          2020-10-05      05f11c          3    2020-08-19  9999-99-99

[134817048 rows x 5 columns]

In [ ]:
#Tabla de frecuencia de los IDs

appended_data['ID_REGISTRO'].value_counts()
#appended_data.groupby('ID_REGISTRO').nunique()

In [5]:
#Borrar duplicados
unique_results = appended_data.drop_duplicates(subset=["ID_REGISTRO", "RESULTADO"],keep="first")
unique_results

        FECHA_ACTUALIZACION ID_REGISTRO  RESULTADO FECHA_INGRESO   FECHA_DEF
0                2020-04-19      09e8dc          1    2020-04-09  9999-99-99
1                2020-04-19      0efbaf          1    2020-04-06  9999-99-99
2                2020-04-19      091a48          2    2020-04-06  9999-99-99
3                2020-04-19      1a5595          3    2020-04-15  9999-99-99
4                2020-04-19      13236c          2    2020-04-02  9999-99-99
...                     ...         ...        ...           ...         ...
1758519          2020-10-05      460d56          3    2020-08-22  9999-99-99
1758576          2020-10-05      354004          3    2020-10-04  9999-99-99
1758577          2020-10-05      206daa          3    2020-10-04  9999-99-99
1758578          2020-10-05      3d5b93          3    2020-10-04  9999-99-99
1758579          2020-10-05      4060ae          3    2020-10-04  9999-99-99

[3362240 rows x 5 columns]

In [15]:
unique_results.dtypes

FECHA_ACTUALIZACION    object
ID_REGISTRO            object
RESULTADO               int64
FECHA_INGRESO          object
FECHA_DEF              object
dtype: object

In [16]:
fecha_act = pd.to_datetime(pd.Series(unique_results.FECHA_ACTUALIZACION))

In [17]:
unique_results['dias']=datetime.strftime(unique_results['FECHA_ACTUALIZACION'],'%y-%m-%d')
-datetime.strptime(unique_results['FECHA_INGRESO'],'%y-%m-%d')

TypeError: descriptor 'strftime' for 'datetime.date' objects doesn't apply to a 'Series' object

In [17]:
#Base agrupada por ID_REGISTRO, RESULTADO y FECHA_INGRESO
grouped_db=appended_data.groupby(['ID_REGISTRO','RESULTADO','FECHA_INGRESO'])['FECHA_ACTUALIZACION'].value_counts().unstack().fillna(0)
grouped_db

FECHA_ACTUALIZACION                  2020-04-19  2020-04-20  2020-04-21  \
ID_REGISTRO RESULTADO FECHA_INGRESO
000001      2         2020-08-04            0.0         0.0         0.0
000002      1         2020-06-26            0.0         0.0         0.0
            3         2020-06-26            0.0         0.0         0.0
000003      1         2020-08-20            0.0         0.0         0.0
            3         2020-08-20            0.0         0.0         0.0
...                                         ...         ...         ...
zzb8a2      2         2020-06-03            0.0         0.0         0.0
zzf49f      2         2020-05-20            0.0         0.0         0.0
zzf4ec      2         2020-07-09            0.0         0.0         0.0
zzf571      2         2020-06-16            0.0         0.0         0.0
            3         2020-06-16            0.0         0.0         0.0

FECHA_ACTUALIZACION                  2020-04-22  2020-04-23  2020-04-24  \
ID_REGISTRO RESULTADO FECHA_INGRESO
000001      2         2020-08-04            0.0         0.0         0.0
000002      1         2020-06-26            0.0         0.0         0.0
            3         2020-06-26            0.0         0.0         0.0
000003      1         2020-08-20            0.0         0.0         0.0
            3         2020-08-20            0.0         0.0         0.0
...                                         ...         ...         ...
zzb8a2      2         2020-06-03            0.0         0.0         0.0
zzf49f      2         2020-05-20            0.0         0.0         0.0
zzf4ec      2         2020-07-09            0.0         0.0         0.0
zzf571      2         2020-06-16            0.0         0.0         0.0
            3         2020-06-16            0.0         0.0         0.0

FECHA_ACTUALIZACION                  2020-04-25  2020-04-26  2020-04-27  \
ID_REGISTRO RESULTADO FECHA_INGRESO
000001      2         2020-08-04            0.0         0.0         0.0
000002      1         2020-06-26            0.0         0.0         0.0
            3         2020-06-26            0.0         0.0         0.0
000003      1         2020-08-20            0.0         0.0         0.0
            3         2020-08-20            0.0         0.0         0.0
...                                         ...         ...         ...
zzb8a2      2         2020-06-03            0.0         0.0         0.0
zzf49f      2         2020-05-20            0.0         0.0         0.0
zzf4ec      2         2020-07-09            0.0         0.0         0.0
zzf571      2         2020-06-16            0.0         0.0         0.0
            3         2020-06-16            0.0         0.0         0.0

FECHA_ACTUALIZACION                  2020-04-28  ...  2020-09-26  2020-09-27  \
ID_REGISTRO RESULTADO FECHA_INGRESO              ...
000001      2         2020-08-04            0.0  ...         1.0         1.0
000002      1         2020-06-26            0.0  ...         1.0         1.0
            3         2020-06-26            0.0  ...         0.0         0.0
000003      1         2020-08-20            0.0  ...         1.0         1.0
            3         2020-08-20            0.0  ...         0.0         0.0
...                                         ...  ...         ...         ...
zzb8a2      2         2020-06-03            0.0  ...         1.0         1.0
zzf49f      2         2020-05-20            0.0  ...         1.0         1.0
zzf4ec      2         2020-07-09            0.0  ...         0.0         0.0
zzf571      2         2020-06-16            0.0  ...         1.0         1.0
            3         2020-06-16            0.0  ...         0.0         0.0

FECHA_ACTUALIZACION                  2020-09-28  2020-09-29  2020-09-30  \
ID_REGISTRO RESULTADO FECHA_INGRESO
000001      2         2020-08-04            1.0         1.0         1.0
000002      1         2020-06-26            1.0         1.0         1.0
            3         2020-06-26            0.0         0.0         0.0
000003      1         2020-08-20            1.0         1.0         1.0
            3         2020-08-20            0.0         0.0         0.0
...                                         ...         ...         ...
zzb8a2      2         2020-06-03            1.0         1.0         1.0
zzf49f      2         2020-05-20            1.0         1.0         1.0
zzf4ec      2         2020-07-09            0.0         0.0         0.0
zzf571      2         2020-06-16            1.0         1.0         1.0
            3         2020-06-16            0.0         0.0         0.0

FECHA_ACTUALIZACION                  2020-10-01  2020-10-02  2020-10-03  \
ID_REGISTRO RESULTADO FECHA_INGRESO
000001      2         2020-08-04            1.0         1.0         1.0
000002      1         2020-06-26            1.0         1.0         1.0
            3         2020-06-26            0.0         0.0         0.0
000003      1         2020-08-20            1.0         1.0         1.0
            3         2020-08-20            0.0         0.0         0.0
...                                         ...         ...         ...
zzb8a2      2         2020-06-03            1.0         1.0         1.0
zzf49f      2         2020-05-20            1.0         1.0         1.0
zzf4ec      2         2020-07-09            0.0         0.0         0.0
zzf571      2         2020-06-16            1.0         1.0         1.0
            3         2020-06-16            0.0         0.0         0.0

FECHA_ACTUALIZACION                  2020-10-04  2020-10-05
ID_REGISTRO RESULTADO FECHA_INGRESO
000001      2         2020-08-04            1.0         1.0
000002      1         2020-06-26            1.0         1.0
            3         2020-06-26            0.0         0.0
000003      1         2020-08-20            1.0         1.0
            3         2020-08-20            0.0         0.0
...                                         ...         ...
zzb8a2      2         2020-06-03            1.0         1.0
zzf49f      2         2020-05-20            1.0         1.0
zzf4ec      2         2020-07-09            0.0         0.0
zzf571      2         2020-06-16            1.0         1.0
            3         2020-06-16            0.0         0.0

[3370203 rows x 170 columns]

In [9]:
#A partir de una fecha cercana de fecha de ingreso (para ver con qué valor de RESULTADO entran a la base)
filtered_db = appended_data[pd.to_datetime(appended_data['FECHA_INGRESO'])>datetime(2020,9,30)]

filtered_db.to_csv(r"/Users/dcastanog/Desktop/Python/filtered_db.csv")

In [27]:
id_result=filtered_db[['ID_REGISTRO','RESULTADO']]
id_result.groupby(['ID_REGISTRO'])['RESULTADO'].value_counts() .unstack().fillna(0)

RESULTADO      1    2    3
ID_REGISTRO
00b149       0.0  0.0  7.0
011e2c       6.0  0.0  3.0
0250d5       0.0  5.0  4.0
067f7f       0.0  6.0  1.0
068dac       0.0  7.0  0.0
...          ...  ...  ...
467ebb       4.0  0.0  1.0
467ec2       1.0  0.0  6.0
467edd       0.0  0.0  7.0
z13788       5.0  0.0  0.0
z5ac3a       5.0  0.0  0.0

[164305 rows x 3 columns]

In [69]:
####### Pregunta: ¿Con qué RESULTADO registran a una persona el primer día que aparece en la base?

#Bases de datos de dos días seguidos 
path = '/Users/dcastanog/Library/Mobile Documents/com~apple~CloudDocs/CIC-19/Pruebas/septiembre/'
t = pd.Series(np.arange(datetime(2020,9,11), datetime(2020,9,13),timedelta(days=1)).astype(datetime),name='fecha')
df = {}
for i,date in enumerate(t): 
 print(path+t[i].strftime('%y%m%d')+'COVID19MEXICO'+'.csv')
 df[i] = pd.read_csv(path+t[i].strftime('%y%m%d')+'COVID19MEXICO'+'.csv',encoding='latin1')

/Users/dcastanog/Library/Mobile Documents/com~apple~CloudDocs/CIC-19/Pruebas/septiembre/200911COVID19MEXICO.csv
/Users/dcastanog/Library/Mobile Documents/com~apple~CloudDocs/CIC-19/Pruebas/septiembre/200912COVID19MEXICO.csv

In [70]:
#Bases con solo IDs
registros0=df[0][['ID_REGISTRO']]
registros0

        ID_REGISTRO
0            1779cd
1            05a196
2            08f0e2
3            100180
4            1622ec
...             ...
1496317      07e441
1496318      1d2096
1496319      11d225
1496320      001a50
1496321      134b79

[1496322 rows x 1 columns]

In [71]:
registros1=df[1][['ID_REGISTRO']]
registros1

        ID_REGISTRO
0            114cd3
1            0bafd8
2            18747a
3            174174
4            0eae86
...             ...
1510306      0978f0
1510307      00cc83
1510308      00ff2a
1510309      0cfcd0
1510310      1bddbd

[1510311 rows x 1 columns]

In [72]:
new_regs = registros0.merge(registros1, how = 'outer' ,indicator=True).loc[lambda x : x['_merge']=='left_only']
new_regs2=new_regs.drop(columns=['_merge'])
new_regs2

        ID_REGISTRO
32663        06534d
86431        0aebf1
115704       0b0a5b
158468       0b1dd3
182301       154ec4
...             ...
1494636      1d6807
1494820      2fcbe5
1495001      1e3b2f
1496066      369f02
1496167      28ea8f

[443 rows x 1 columns]

In [73]:
new_regs3=pd.merge(new_regs2,df[0],on='ID_REGISTRO',how='inner')
new_regs3

,ID_REGISTRO,FECHA_ACTUALIZACION,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,06534d,2020-09-11,2,12,9,2,9,9,12,1,...,2,2,2,2,2,1,99,MÃ©xico,99,97
1,0aebf1,2020-09-11,1,12,14,2,14,14,23,1,...,2,2,2,2,1,1,99,MÃ©xico,99,97
2,0b0a5b,2020-09-11,2,12,15,2,15,15,39,2,...,2,2,2,2,2,1,99,MÃ©xico,99,2
3,0b1dd3,2020-09-11,2,9,30,1,30,30,87,1,...,2,2,2,2,2,1,99,MÃ©xico,99,97
4,154ec4,2020-09-11,2,12,9,1,9,9,10,1,...,2,2,2,2,1,1,99,MÃ©xico,99,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,1d6807,2020-09-11,1,4,2,2,25,2,2,2,...,2,2,2,2,2,3,99,MÃ©xico,99,2
439,2fcbe5,2020-09-11,2,9,14,1,14,14,120,1,...,2,2,2,2,1,3,99,MÃ©xico,99,97
440,1e3b2f,2020-09-11,1,12,26,2,26,26,30,1,...,2,2,2,1,2,3,99,MÃ©xico,99,97
441,369f02,2020-09-11,2,4,9,2,15,9,10,1,...,2,2,2,2,2,3,99,MÃ©xico,99,97
442,28ea8f,2020-09-11,2,4,11,1,11,11,20,1,...,2,1,2,2,2,3,99,MÃ©xico,99,97

In [74]:
new_regs_resultado3=new_regs3[new_regs3['RESULTADO']==3]
new_regs_resultado3

,ID_REGISTRO,FECHA_ACTUALIZACION,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
24,0f24e2,2020-09-11,2,4,2,1,16,2,2,1,...,2,2,2,2,99,3,99,MÃ©xico,99,97
25,1ba2fd,2020-09-11,2,4,2,2,2,2,2,1,...,2,2,2,2,99,3,99,MÃ©xico,99,97
26,101485,2020-09-11,2,6,9,1,9,9,12,1,...,2,1,2,2,1,3,99,MÃ©xico,99,97
27,16f39a,2020-09-11,2,4,2,2,2,2,2,1,...,2,2,2,2,99,3,99,MÃ©xico,99,97
28,02ec88,2020-09-11,2,9,9,2,14,9,10,2,...,2,2,1,2,2,3,99,MÃ©xico,99,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,1d6807,2020-09-11,1,4,2,2,25,2,2,2,...,2,2,2,2,2,3,99,MÃ©xico,99,2
439,2fcbe5,2020-09-11,2,9,14,1,14,14,120,1,...,2,2,2,2,1,3,99,MÃ©xico,99,97
440,1e3b2f,2020-09-11,1,12,26,2,26,26,30,1,...,2,2,2,1,2,3,99,MÃ©xico,99,97
441,369f02,2020-09-11,2,4,9,2,15,9,10,1,...,2,2,2,2,2,3,99,MÃ©xico,99,97
442,28ea8f,2020-09-11,2,4,11,1,11,11,20,1,...,2,1,2,2,2,3,99,MÃ©xico,99,97

In [107]:
new_regs_resultado1=new_regs3[new_regs3['RESULTADO']==1]
new_regs_resultado1.ID_REGISTRO.unique()

array(['06534d', '0aebf1', '0b0a5b', '0b1dd3', '154ec4', '03dc93',
       '0901ee', '0e9a43', '276c7e', '14379b', '304a9e', '0bc95a',
       '0c59e9', '0b7231', '336ada', '13b909', '1e86b9', '374218',
       '0432e8', '19830c', '099fc3', '0596ce', '40e14a', '0aadc0',
       '174961'], dtype=object)

In [76]:
new_regs_resultado2=new_regs3[new_regs3['RESULTADO']==2]
new_regs_resultado2

,ID_REGISTRO,FECHA_ACTUALIZACION,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
8,12b76e,2020-09-11,2,6,9,1,15,15,57,2,...,98,1,2,2,1,2,99,MÃ©xico,99,2
9,041383,2020-09-11,2,12,16,1,16,16,53,1,...,2,2,2,2,1,2,99,MÃ©xico,99,97
10,1a2b7d,2020-09-11,2,12,9,1,9,9,4,1,...,2,2,2,2,1,2,99,MÃ©xico,99,97
11,005114,2020-09-11,2,12,15,1,15,15,120,1,...,2,2,2,2,1,2,99,MÃ©xico,99,97
12,07acdc,2020-09-11,1,6,16,2,15,16,53,2,...,2,2,2,2,1,2,99,MÃ©xico,99,2
13,0b1b5b,2020-09-11,2,9,15,2,15,9,10,2,...,1,2,2,2,2,2,99,MÃ©xico,99,2
14,0b2787,2020-09-11,2,12,16,1,16,16,69,1,...,2,2,2,2,1,2,99,MÃ©xico,99,97
15,0d1387,2020-09-11,2,6,9,1,9,15,58,1,...,98,98,98,98,2,2,99,MÃ©xico,99,97
16,09d093,2020-09-11,2,6,9,1,9,15,120,1,...,2,2,2,2,2,2,99,MÃ©xico,99,97
17,0b0263,2020-09-11,2,12,15,1,20,15,39,2,...,2,1,2,2,1,2,99,MÃ©xico,99,2
18,0d59a4,2020-09-11,2,12,16,1,16,16,102,1,...,2,2,2,2,2,2,99,MÃ©xico,99,97
19,0d5bcf,2020-09-11,2,9,22,2,11,22,11,1,...,2,2,2,2,2,2,99,MÃ©xico,99,97
20,1dc104,2020-09-11,2,6,9,1,9,15,70,1,...,2,1,2,2,1,2,99,MÃ©xico,99,97
21,184368,2020-09-11,2,12,16,2,16,16,53,1,...,2,2,2,2,2,2,99,MÃ©xico,99,97
22,148973,2020-09-11,2,12,16,1,16,16,88,1,...,2,2,2,2,1,2,99,MÃ©xico,99,97
23,01f039,2020-09-11,1,12,16,1,16,16,108,1,...,2,2,2,1,1,2,99,MÃ©xico,99,97
124,16b4b6,2020-09-11,2,12,10,1,10,10,5,1,...,2,2,2,2,1,2,99,MÃ©xico,99,97
125,20ab6a,2020-09-11,2,4,9,1,9,15,121,1,...,2,2,2,2,2,2,99,MÃ©xico,99,97
126,16f045,2020-09-11,2,12,16,1,16,16,53,1,...,2,2,2,2,1,2,99,MÃ©xico,99,97
127,0eaef7,2020-09-11,1,4,9,1,9,9,10,1,...,2,2,2,2,2,2,99,MÃ©xico,99,97
128,0f662d,2020-09-11,2,6,9,2,21,9,5,2,...,98,98,98,98,99,2,99,MÃ©xico,99,2
129,126e3b,2020-09-11,1,4,22,2,9,22,14,2,...,2,2,2,2,99,2,99,MÃ©xico,99,2
130,0f0154,2020-09-11,2,12,9,1,15,15,81,2,...,2,2,2,2,2,2,99,MÃ©xico,99,2
131,07672a,2020-09-11,2,6,9,1,9,9,5,2,...,2,1,2,2,2,2,99,MÃ©xico,99,2

In [106]:
#Para saber qué pasa con los que entraron con RESULTADO=1 el 11 de septiembre??
filtered_11sep = appended_data[pd.to_datetime(appended_data['FECHA_ACTUALIZACION'])>datetime(2020,9,10)]
filtered_11sep

        FECHA_ACTUALIZACION ID_REGISTRO  RESULTADO FECHA_INGRESO
0                2020-09-11      1779cd          1    2020-05-27
1                2020-09-11      05a196          1    2020-03-30
2                2020-09-11      08f0e2          1    2020-04-12
3                2020-09-11      100180          1    2020-05-06
4                2020-09-11      1622ec          1    2020-05-10
...                     ...         ...        ...           ...
1758577          2020-10-05      206daa          3    2020-10-04
1758578          2020-10-05      3d5b93          3    2020-10-04
1758579          2020-10-05      4060ae          3    2020-10-04
1758580          2020-10-05      3f1bc7          3    2020-09-28
1758581          2020-10-05      05f11c          3    2020-08-19

[40637012 rows x 4 columns]

In [110]:
unos = filtered_11sep[
        (filtered_11sep['ID_REGISTRO'] == '06534d') &
        (filtered_11sep['ID_REGISTRO'] != '0aebf1') ]
unos

      FECHA_ACTUALIZACION ID_REGISTRO  RESULTADO FECHA_INGRESO
32663          2020-09-11      06534d          1    2020-06-05

In [ ]:
, , '0b0a5b', '0b1dd3', '154ec4', '03dc93',
       '0901ee', '0e9a43', '276c7e', '14379b', '304a9e', '0bc95a',
       '0c59e9', '0b7231', '336ada', '13b909', '1e86b9', '374218',
       '0432e8', '19830c', '099fc3', '0596ce', '40e14a', '0aadc0',
       '174961'],

In [102]:
acomodada=filtered_11sep.groupby(['ID_REGISTRO','RESULTADO','FECHA_INGRESO'])['FECHA_ACTUALIZACION'].value_counts().unstack().fillna(0)
acomodada.to_csv(path+'unos.csv')

In [103]:
acomodada

FECHA_ACTUALIZACION                  2020-09-11  2020-09-12  2020-09-13  \
ID_REGISTRO RESULTADO FECHA_INGRESO
000001      2         2020-08-04            1.0         1.0         1.0
000002      1         2020-06-26            1.0         1.0         1.0
000003      1         2020-08-20            1.0         1.0         1.0
000004      2         2020-07-15            1.0         1.0         1.0
000005      2         2020-07-18            1.0         1.0         1.0
...                                         ...         ...         ...
zz9040      1         2020-09-06            1.0         1.0         1.0
zzb8a2      2         2020-06-03            1.0         1.0         1.0
zzf49f      2         2020-05-20            1.0         1.0         1.0
zzf571      2         2020-06-16            0.0         0.0         0.0
            3         2020-06-16            1.0         1.0         1.0

FECHA_ACTUALIZACION                  2020-09-14  2020-09-15  2020-09-16  \
ID_REGISTRO RESULTADO FECHA_INGRESO
000001      2         2020-08-04            1.0         1.0         1.0
000002      1         2020-06-26            1.0         1.0         1.0
000003      1         2020-08-20            1.0         1.0         1.0
000004      2         2020-07-15            1.0         1.0         1.0
000005      2         2020-07-18            1.0         1.0         1.0
...                                         ...         ...         ...
zz9040      1         2020-09-06            1.0         1.0         1.0
zzb8a2      2         2020-06-03            1.0         1.0         1.0
zzf49f      2         2020-05-20            1.0         1.0         1.0
zzf571      2         2020-06-16            0.0         0.0         0.0
            3         2020-06-16            1.0         1.0         1.0

FECHA_ACTUALIZACION                  2020-09-17  2020-09-18  2020-09-19  \
ID_REGISTRO RESULTADO FECHA_INGRESO
000001      2         2020-08-04            1.0         1.0         1.0
000002      1         2020-06-26            1.0         1.0         1.0
000003      1         2020-08-20            1.0         1.0         1.0
000004      2         2020-07-15            1.0         1.0         1.0
000005      2         2020-07-18            1.0         1.0         1.0
...                                         ...         ...         ...
zz9040      1         2020-09-06            1.0         1.0         1.0
zzb8a2      2         2020-06-03            1.0         1.0         1.0
zzf49f      2         2020-05-20            1.0         1.0         1.0
zzf571      2         2020-06-16            0.0         0.0         0.0
            3         2020-06-16            1.0         1.0         1.0

FECHA_ACTUALIZACION                  2020-09-20  ...  2020-09-26  2020-09-27  \
ID_REGISTRO RESULTADO FECHA_INGRESO              ...
000001      2         2020-08-04            1.0  ...         1.0         1.0
000002      1         2020-06-26            1.0  ...         1.0         1.0
000003      1         2020-08-20            1.0  ...         1.0         1.0
000004      2         2020-07-15            1.0  ...         1.0         1.0
000005      2         2020-07-18            1.0  ...         1.0         1.0
...                                         ...  ...         ...         ...
zz9040      1         2020-09-06            1.0  ...         1.0         1.0
zzb8a2      2         2020-06-03            1.0  ...         1.0         1.0
zzf49f      2         2020-05-20            1.0  ...         1.0         1.0
zzf571      2         2020-06-16            0.0  ...         1.0         1.0
            3         2020-06-16            1.0  ...         0.0         0.0

FECHA_ACTUALIZACION                  2020-09-28  2020-09-29  2020-09-30  \
ID_REGISTRO RESULTADO FECHA_INGRESO
000001      2         2020-08-04            1.0         1.0         1.0
000002      1         2020-06-26            1.0         1.0         1.0
000003      1         2020-08-20            1.0         1.0         1.0
000004      2         2020-07-15            1.0         1.0         1.0
000005      2         2020-07-18            1.0         1.0         1.0
...                                         ...         ...         ...
zz9040      1         2020-09-06            1.0         1.0         1.0
zzb8a2      2         2020-06-03            1.0         1.0         1.0
zzf49f      2         2020-05-20            1.0         1.0         1.0
zzf571      2         2020-06-16            1.0         1.0         1.0
            3         2020-06-16            0.0         0.0         0.0

FECHA_ACTUALIZACION                  2020-10-01  2020-10-02  2020-10-03  \
ID_REGISTRO RESULTADO FECHA_INGRESO
000001      2         2020-08-04            1.0         1.0         1.0
000002      1         2020-06-26            1.0         1.0         1.0
000003      1         2020-08-20            1.0         1.0         1.0
000004      2         2020-07-15            1.0         1.0         1.0
000005      2         2020-07-18            1.0         1.0         1.0
...                                         ...         ...         ...
zz9040      1         2020-09-06            1.0         1.0         1.0
zzb8a2      2         2020-06-03            1.0         1.0         1.0
zzf49f      2         2020-05-20            1.0         1.0         1.0
zzf571      2         2020-06-16            1.0         1.0         1.0
            3         2020-06-16            0.0         0.0         0.0

FECHA_ACTUALIZACION                  2020-10-04  2020-10-05
ID_REGISTRO RESULTADO FECHA_INGRESO
000001      2         2020-08-04            1.0         1.0
000002      1         2020-06-26            1.0         1.0
000003      1         2020-08-20            1.0         1.0
000004      2         2020-07-15            1.0         1.0
000005      2         2020-07-18            1.0         1.0
...                                         ...         ...
zz9040      1         2020-09-06            1.0         1.0
zzb8a2      2         2020-06-03            1.0         1.0
zzf49f      2         2020-05-20            1.0         1.0
zzf571      2         2020-06-16            1.0         1.0
            3         2020-06-16            0.0         0.0

[2012570 rows x 25 columns]